set projloc=C:\Users\user\Desktop\Our_I3306_Project\LibraryDatabase\
set conn=-S Mhamad-Ayoub -U sa -P Ayoub123? -w 300
cls
echo Begining on top of MS Sqlserver DBMS engine...

echo create table...
osql %conn% -i %projloc%\SQL\createTables.sql -o %projloc%\Log\createTables.log

echo create triggers....
osql %conn% -i %projloc%\SQL\createTriggers.sql -o %projloc%\Log\createTriggers.log

echo crete indexes....
osql %conn% -i %projloc%\SQL\createIndexes.sql -o %projloc%\Log\createIndexes.log

echo End of batch file....